name: Update Copyright Year

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 1 1 *'  # Runs on January 1st every year
  workflow_dispatch:

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update copyright year
        run: |
          YEAR=$(date +%Y)  # This should get 2025
          echo "Current year is: $YEAR"  # Add this for debugging
          find . -type f -name "LICENSE*" -exec sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) ${YEAR}/" {} +
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: update copyright year'
          commit-message: 'chore: update copyright year'
          branch: update-copyright-year
