name: Update Copyright Year

on:
  schedule:
    - cron: '0 0 1 1 *'  # Runs on January 1st every year
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update copyright year
        run: |
          YEAR=$(date +%Y)
          find . -type f -name "LICENSE*" -exec sed -i "s/Copyright (c) [0-9]\{4\}/Copyright (c) ${YEAR}/" {} +
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: update copyright year'
          commit-message: 'chore: update copyright year'
          branch: update-copyright-year
